### ISSUE TITLE
Safari is very slow, and appears to lock 

### ISSUE THREAD

**Issue by lingo** [sminnee/salad#1]
Safari is very slow, and appears to lock sometimes when using sapphire salad. This may have something to do with changing input focus under OSX?

**Comment by sminnee** [comment]
I believe that this is to do with the ajax waiting.  The "I've completed the ajax response" setting never finishes and so it waits for a timeout.

**Comment by sminnee** [comment]
Luke, do you know if you've fixed this now; it doesn't appear to occur on the test suite.

**Comment by lingo** [comment]
I wasn't able to reproduce this.  So far, it's only occurred on Mike's laptop. Perhaps worth trying on a slow machine?

**Comment by sminnee** [comment]
I think we fixed this.
