### ISSUE TITLE
IFRAMES

### ISSUE THREAD

**Issue by lingo** [sminnee/salad#3]
Salad cannot "see" or "click" anything in an IFrame.

This is best implemented as follows:
1. By default, spider through all **visible** iframes in the page
2. An optional limiter should be allowed on the element-finding rules, eg: 'And I see "xyz" in the iframe "left"' or 'And I click "abc" within the element "tabstrip"'.  These should limit element finding to containers, either DIVs or IFRAMES.

Note that option 2 involves tracking element hierarchy, which may be annoying to implement.

**Comment by sminnee** [comment]
Perhaps we should use the same syntax for both of them?

(command) within "(element or iframe id)"

**Comment by lingo** [comment]
I'm all for minimal vocabulary.  Sounds good.

**Comment by sminnee** [comment]
Heh, pro tip: don't use angle brackets in your github comments.  My previous comment was unintelligible.  We'll need to make sure that the other rules end in something like this to prevent rule ambiguity.

```
 [., \t]*$/
```

**Comment by lingo** [comment]
Alas  "(command) within (element or iframe id)" causes ambiguous matching.

**Comment by lingo** [comment]
Another option is:
     Given I examine the element "Iframe_1"
     And I see "text within frame"

**Comment by sminnee** [comment]
Does "(command) within (element or iframe id)" only cause ambiguous matching, because we don't have this at the end of all the other rules?

```
 [., \t]*$/
```

**Comment by lingo** [comment]
This is something I'm wondering about -- whether if we anchor our other rules properly, we will avoid the issue.  I hope so!

**Comment by sminnee** [comment]
OK, this syntax works now

```
    Given I click "ID_RadioB" within "IFrame1"
```

I updated all the rules with the suffix described.  It might be nicer to amend the Cucumber code to automatically append this to all rules, but this'll do for now.

See 54523ac40443491f8d62b6ada690ab4c1f400907
